export default  {
  FETCHED_BOOKS_SERVER:'FETCHED_BOOKS_SERVER',
  CHANGE_BOOK_PANEL:'CHANGE_BOOK_PANEL',
  POSTED_BOOKS_SERVER:'POST_BOOKS_SERVER',
  SET_SEARCH:'SET_SEARCH',
  FETCHED_BOOK_COUNT:'FETCHED_BOOK_COUNT'
}